export { default as ConnectButton } from './components/ConnectButton.vue'
export { useWallet, type UseWalletReturn } from './composables/use-wallet'
export { WalletConnectInjectionKey } from './context/injection-key'
export { useWalletContext } from './context/use-wallet-context'
export { WalletConnectPlugin } from './plugin/wallet-connect-plugin'
