import bs58 from 'bs58'
import nacl from 'tweetnacl'

import type { WalletConfig } from '../wallets/sorter'

/** Solana cluster identifier sent to the wallet so it can pick its RPC. */
export type SolanaCluster = 'mainnet-beta' | 'devnet'

/**
 * x25519 (NaCl box) keypair used to encrypt the redirect-callback payload.
 * Phantom and Solflare require this — the wallet encrypts its response with
 * the dapp's `publicKey`, and the dapp decrypts with `secretKey` on return.
 *
 * Treat `secretKey` as confidential. The pair is single-use per redirect
 * round-trip; never reuse one across sessions.
 */
export interface EphemeralKeypair {
  /** 32-byte x25519 public key. */
  publicKey: Uint8Array
  /**
   * 32-byte x25519 secret key — never log, never reuse. Persist alongside
   * the `PendingState` (TASK-103) via the SessionStore so the callback
   * (TASK-106) can decrypt the response on the next page load.
   */
  secretKey: Uint8Array
}

/** Inputs accepted by {@link buildConnectUrl}. */
export interface ConnectOptions {
  /**
   * Absolute HTTPS URL the wallet redirects back to with its encrypted
   * response (the dapp's callback page). Must be absolute — relative URLs
   * throw.
   */
  redirectUrl: string
  /** Absolute URL of the dapp; shown by the wallet in its connect prompt. */
  appUrl: string
  /** Cluster the wallet should connect to. */
  cluster: SolanaCluster
  /**
   * Keypair generated by {@link generateEphemeralKeypair} for this round-trip.
   * Persist `secretKey` (e.g., to `sessionStorage` via the SessionStore) so
   * the callback can decrypt the response on the next page load.
   */
  ephemeralKeypair: EphemeralKeypair
}

/**
 * Inputs accepted by {@link buildSignAndConnectUrl}. Adds the SIWS message
 * to be signed in the same redirect.
 */
export interface SignConnectOptions extends ConnectOptions {
  /**
   * The Sign-In With Solana message text the wallet should display and sign.
   * Passed as a `sign_in_message` query param. Wallets that do not yet
   * support the combined endpoint will ignore it; in that case the dapp
   * must follow up with a separate sign-message redirect (handled by the
   * `DeepLinkAdapter`).
   */
  signInMessage: string
}

const VALID_CLUSTERS: ReadonlySet<SolanaCluster> = new Set(['mainnet-beta', 'devnet'])
const X25519_KEY_BYTES = 32

/**
 * Generate a fresh x25519 keypair via `tweetnacl`. Internally calls
 * `nacl.randomBytes` which uses `crypto.getRandomValues` on browsers and
 * Node's `crypto` on the server — never `Math.random`.
 */
export function generateEphemeralKeypair(): EphemeralKeypair {
  const pair = nacl.box.keyPair()
  return { publicKey: pair.publicKey, secretKey: pair.secretKey }
}

/**
 * Build the deep-link URL that the dapp navigates to in order to start a
 * connect flow on a mobile wallet. The URL follows Phantom's Universal
 * Link API spec (Solflare and Opindex use the same parameter shape):
 *
 *   `<wallet.universalLink>?dapp_encryption_public_key=...&cluster=...&app_url=...&redirect_link=...`
 *
 * Throws if `redirectUrl` / `appUrl` are not absolute http(s) URLs, if
 * `cluster` is not `'mainnet-beta'` or `'devnet'`, or if the public key
 * is not exactly 32 bytes.
 */
export function buildConnectUrl(wallet: WalletConfig, options: ConnectOptions): string {
  return appendParams(wallet.universalLink, buildBaseParams(options))
}

/**
 * Build the deep-link URL that bundles a SIWS message with the connect
 * step. Identical to {@link buildConnectUrl} plus a `sign_in_message`
 * query param.
 *
 * @experimental Phantom's current `/ul/v1/connect` endpoint does not
 * actually consume `sign_in_message`; this is forward-compat for wallets
 * that adopt a combined connect-and-sign endpoint. The `DeepLinkAdapter`
 * (TASK-108) handles the two-redirect fallback for wallets that don't.
 */
export function buildSignAndConnectUrl(wallet: WalletConfig, options: SignConnectOptions): string {
  const params = buildBaseParams(options)
  params.push(['sign_in_message', options.signInMessage])
  return appendParams(wallet.universalLink, params)
}

type QueryEntry = readonly [string, string]

function buildBaseParams(options: ConnectOptions): QueryEntry[] {
  assertAbsoluteUrl(options.redirectUrl, 'redirectUrl')
  assertAbsoluteUrl(options.appUrl, 'appUrl')
  assertCluster(options.cluster)
  assertX25519PublicKey(options.ephemeralKeypair.publicKey)
  return [
    ['dapp_encryption_public_key', bs58.encode(options.ephemeralKeypair.publicKey)],
    ['cluster', options.cluster],
    ['app_url', options.appUrl],
    ['redirect_link', options.redirectUrl],
  ]
}

/**
 * Join entries onto `base` with explicit `encodeURIComponent` per value —
 * unlike `URLSearchParams.toString()` this produces `%20` (not `+`) for
 * spaces, which is the canonical RFC-3986 form expected across wallet
 * deep-link APIs.
 *
 * Handles three `base` shapes:
 * - no `?` → append `?` then the query
 * - ends with bare `?` → append the query (no separator)
 * - has `?` followed by content → append `&` then the query
 */
function appendParams(base: string, entries: ReadonlyArray<QueryEntry>): string {
  const query = entries
    .map(([k, v]) => `${encodeURIComponent(k)}=${encodeURIComponent(v)}`)
    .join('&')
  if (base.endsWith('?')) return `${base}${query}`
  const separator = base.includes('?') ? '&' : '?'
  return `${base}${separator}${query}`
}

function assertAbsoluteUrl(value: string, fieldName: string): void {
  let url: URL
  try {
    url = new URL(value)
  } catch {
    throw new Error(`${fieldName} must be an absolute http(s) URL; got '${value}'`)
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error(`${fieldName} must use http(s); got '${url.protocol}'`)
  }
}

function assertCluster(cluster: string): void {
  if (!VALID_CLUSTERS.has(cluster as SolanaCluster)) {
    throw new Error(`cluster must be 'mainnet-beta' or 'devnet'; got '${cluster}'`)
  }
}

function assertX25519PublicKey(key: Uint8Array): void {
  if (key.length !== X25519_KEY_BYTES) {
    throw new Error(
      `ephemeralKeypair.publicKey must be ${X25519_KEY_BYTES} bytes; got ${key.length}`,
    )
  }
}
